questions = [
    {"question": 'What does CPU stand for?',
     "options": ['Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Utility'],
     "answer": 'Central Processing Unit'},
    {"question": 'Which data structure uses LIFO (Last In, First Out) order?',
     "options": ['Queue', 'Stack', 'Array', 'Linked List'],
     "answer": 'Stack'},
    {"question": 'Which data structure uses FIFO (First In, First Out) order?',
     "options": ['Stack', 'Tree', 'Queue', 'Graph'],
     "answer": 'Queue'},
    {"question": 'What is the binary representation of the decimal number 5?',
     "options": ['100', '101', '110', '111'],
     "answer": '101'},
    {"question": 'What is the time complexity of binary search on a sorted array of n elements?',
     "options": ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'],
     "answer": 'O(log n)'},
    {"question": 'Which of these is NOT a common HTTP method?',
     "options": ['GET', 'POST', 'FETCH', 'DELETE'],
     "answer": 'FETCH'},
    {"question": "What does 'API' stand for?",
     "options": ['Application Programming Interface', 'Advanced Program Integration', 'Automated Process Interaction', 'Application Process Index'],
     "answer": 'Application Programming Interface'},
    {"question": 'Which number system uses only digits 0 and 1?',
     "options": ['Decimal', 'Hexadecimal', 'Octal', 'Binary'],
     "answer": 'Binary'},
    {"question": 'In version control systems, what is the term for combining changes from different branches?',
     "options": ['Fork', 'Merge', 'Clone', 'Commit'],
     "answer": 'Merge'},
    {"question": "What does 'SQL' primarily deal with?",
     "options": ['Styling web pages', 'Managing databases', 'Networking protocols', 'Image processing'],
     "answer": 'Managing databases'},
    {"question": "What does 'RAM' stand for?",
     "options": ['Random Access Memory', 'Read Access Module', 'Rapid Application Memory', 'Runtime Allocation Memory'],
     "answer": 'Random Access Memory'},
    {"question": 'Which data structure represents hierarchical relationships, like a file system?',
     "options": ['Queue', 'Stack', 'Tree', 'Array'],
     "answer": 'Tree'},
    {"question": 'What is the worst-case time complexity of bubble sort?',
     "options": ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
     "answer": 'O(n^2)'},
    {"question": "What does 'HTTP' stand for?",
     "options": ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Transmission Process', 'Host Transfer Text Program'],
     "answer": 'HyperText Transfer Protocol'},
    {"question": 'Which port number is conventionally used by HTTPS?',
     "options": ['21', '80', '443', '8080'],
     "answer": '443'},
    {"question": "What does 'DNS' stand for?",
     "options": ['Domain Name System', 'Data Network Service', 'Digital Naming Standard', 'Domain Network Server'],
     "answer": 'Domain Name System'},
    {"question": 'What is the term for a function that calls itself?',
     "options": ['Iteration', 'Recursion', 'Reflection', 'Inheritance'],
     "answer": 'Recursion'},
    {"question": 'In object-oriented programming, what is the mechanism where a class derives properties from another class called?',
     "options": ['Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'],
     "answer": 'Inheritance'},
    {"question": "Which OOP concept restricts direct access to an object's internal state?",
     "options": ['Polymorphism', 'Inheritance', 'Encapsulation', 'Abstraction'],
     "answer": 'Encapsulation'},
    {"question": "What does 'JSON' stand for?",
     "options": ['JavaScript Object Notation', 'Java Standard Object Network', 'JavaScript Oriented Network', 'Joined Script Object Notation'],
     "answer": 'JavaScript Object Notation'},
    {"question": 'Which of these is a NoSQL database?',
     "options": ['MySQL', 'PostgreSQL', 'MongoDB', 'SQLite'],
     "answer": 'MongoDB'},
    {"question": 'What is the primary purpose of a firewall?',
     "options": ['Speed up internet connections', 'Control network traffic based on security rules', 'Store data permanently', 'Compress files'],
     "answer": 'Control network traffic based on security rules'},
    {"question": "What does 'IDE' stand for in software development?",
     "options": ['Internal Data Exchange', 'Integrated Development Environment', 'Interactive Design Editor', 'Independent Data Engine'],
     "answer": 'Integrated Development Environment'},
    {"question": 'Which sorting algorithm has the best average-case time complexity among these?',
     "options": ['Bubble sort', 'Selection sort', 'Merge sort', 'Insertion sort'],
     "answer": 'Merge sort'},
    {"question": "What is a 'hash collision'?",
     "options": ['When a program crashes', 'When two different inputs produce the same hash output', 'When two servers conflict', 'When memory runs out'],
     "answer": 'When two different inputs produce the same hash output'},
    {"question": "What does 'URL' stand for?",
     "options": ['Uniform Resource Locator', 'Universal Reference Link', 'United Resource Locator', 'Uniform Reference Locator'],
     "answer": 'Uniform Resource Locator'},
    {"question": "In computing, what does 'GUI' stand for?",
     "options": ['General User Interface', 'Graphical User Interface', 'Global User Input', 'Generic Universal Interface'],
     "answer": 'Graphical User Interface'},
    {"question": 'What is the term for storing frequently accessed data temporarily for faster retrieval?',
     "options": ['Caching', 'Indexing', 'Compiling', 'Threading'],
     "answer": 'Caching'},
    {"question": 'Which layer of the OSI model is responsible for routing data between networks?',
     "options": ['Physical layer', 'Data Link layer', 'Network layer', 'Application layer'],
     "answer": 'Network layer'},
    {"question": "What does 'CRUD' stand for in software development?",
     "options": ['Create, Read, Update, Delete', 'Create, Retrieve, Undo, Delete', 'Compile, Run, Update, Debug', 'Copy, Read, Upload, Delete'],
     "answer": 'Create, Read, Update, Delete'},
    {"question": 'What is the primary function of a compiler?',
     "options": ['Execute code line by line', 'Translate source code into machine code', 'Manage memory allocation', 'Debug runtime errors'],
     "answer": 'Translate source code into machine code'},
    {"question": "Which of these best describes an 'interpreter'?",
     "options": ['A program that translates and executes code line by line', 'A hardware component', 'A type of database', 'A network protocol'],
     "answer": 'A program that translates and executes code line by line'},
    {"question": "What does 'IP' stand for in networking?",
     "options": ['Internet Protocol', 'Internal Process', 'Interface Program', 'Information Packet'],
     "answer": 'Internet Protocol'},
    {"question": 'What is the term for a variable that can be accessed from anywhere in a program?',
     "options": ['Local variable', 'Global variable', 'Static variable', 'Private variable'],
     "answer": 'Global variable'},
    {"question": 'Which data structure is best suited for implementing undo functionality?',
     "options": ['Queue', 'Stack', 'Hash table', 'Graph'],
     "answer": 'Stack'},
    {"question": "What does 'GPU' stand for?",
     "options": ['General Processing Unit', 'Graphics Processing Unit', 'Global Processor Utility', 'Graphic Program Unit'],
     "answer": 'Graphics Processing Unit'},
    {"question": 'What is the main purpose of an operating system?',
     "options": ['Write application code', 'Manage hardware and software resources', 'Design websites', 'Compress images'],
     "answer": 'Manage hardware and software resources'},
    {"question": "What does 'CI/CD' commonly stand for in software engineering?",
     "options": ['Continuous Integration / Continuous Deployment', 'Code Inspection / Code Debugging', 'Central Integration / Central Deployment', 'Continuous Interface / Continuous Design'],
     "answer": 'Continuous Integration / Continuous Deployment'},
    {"question": "Which of these best describes 'Big O notation'?",
     "options": ['A way to measure code style', 'A way to describe algorithm efficiency/complexity', 'A programming language', 'A database format'],
     "answer": 'A way to describe algorithm efficiency/complexity'},
    {"question": "What is a 'race condition' in programming?",
     "options": ['A performance benchmark', 'A bug where outcome depends on timing of uncontrolled events', 'A type of sorting algorithm', 'A network speed test'],
     "answer": 'A bug where outcome depends on timing of uncontrolled events'},
    {"question": "What does 'REST' stand for in web APIs?",
     "options": ['Representational State Transfer', 'Remote End State Transfer', 'Reliable Server Transfer', 'Representational System Transfer'],
     "answer": 'Representational State Transfer'},
    {"question": 'Which of these is a version control system?',
     "options": ['Docker', 'Git', 'Kubernetes', 'Nginx'],
     "answer": 'Git'},
    {"question": "What is 'encryption'?",
     "options": ['Deleting data permanently', 'Converting data into a coded form to prevent unauthorized access', 'Compressing data to save space', 'Backing up data to the cloud'],
     "answer": 'Converting data into a coded form to prevent unauthorized access'},
    {"question": "What does 'SSD' stand for?",
     "options": ['Solid State Drive', 'Secure System Data', 'Static Storage Device', 'Server Side Drive'],
     "answer": 'Solid State Drive'},
    {"question": "What is a 'memory leak'?",
     "options": ['When a program uses too much CPU', 'When allocated memory is not released after use', 'When a hard drive fails', 'When network packets are lost'],
     "answer": 'When allocated memory is not released after use'},
    {"question": "Which of these describes a 'binary tree'?",
     "options": ['A tree where each node has at most two children', 'A tree with only two levels', 'A tree used only for sorting numbers', 'A tree with no root'],
     "answer": 'A tree where each node has at most two children'},
    {"question": "What does 'VPN' stand for?",
     "options": ['Virtual Private Network', 'Verified Public Network', 'Virtual Public Node', 'Variable Private Node'],
     "answer": 'Virtual Private Network'},
    {"question": "What is 'multithreading'?",
     "options": ['Running multiple programs on separate computers', 'Executing multiple threads concurrently within a single process', 'Connecting multiple networks together', 'Writing code in multiple languages'],
     "answer": 'Executing multiple threads concurrently within a single process'},
    {"question": "What does 'ORM' stand for in software development?",
     "options": ['Object-Relational Mapping', 'Online Resource Management', 'Operational Runtime Module', 'Object Reference Model'],
     "answer": 'Object-Relational Mapping'},
    {"question": 'Which data structure uses key-value pairs for fast lookup?',
     "options": ['Array', 'Linked list', 'Hash table', 'Stack'],
     "answer": 'Hash table'},
    {"question": "What is 'polymorphism' in object-oriented programming?",
     "options": ['The ability of different classes to be treated through a common interface', 'The process of hiding data', 'A way to allocate memory', 'A type of loop'],
     "answer": 'The ability of different classes to be treated through a common interface'},
    {"question": "What does 'TCP' stand for?",
     "options": ['Transmission Control Protocol', 'Transfer Control Program', 'Total Connection Protocol', 'Terminal Control Process'],
     "answer": 'Transmission Control Protocol'},
    {"question": "Which of these best describes 'refactoring'?",
     "options": ['Adding new features to code', 'Restructuring existing code without changing its external behavior', 'Deleting unused files', 'Deploying code to production'],
     "answer": 'Restructuring existing code without changing its external behavior'},
    {"question": "What is the purpose of a 'load balancer'?",
     "options": ['Encrypt network traffic', 'Distribute incoming traffic across multiple servers', 'Store user sessions', 'Compile source code'],
     "answer": 'Distribute incoming traffic across multiple servers'},
    {"question": "What does 'CDN' stand for?",
     "options": ['Content Delivery Network', 'Central Data Node', 'Computer Data Network', 'Content Distribution Node'],
     "answer": 'Content Delivery Network'},
    {"question": "What is a 'deadlock' in computing?",
     "options": ['A situation where two or more processes wait for each other indefinitely', 'A type of encryption failure', 'A hardware malfunction', 'A network timeout'],
     "answer": 'A situation where two or more processes wait for each other indefinitely'},
    {"question": 'What is the primary purpose of unit testing?',
     "options": ['Test the entire application at once', 'Verify individual components work as expected in isolation', 'Measure server load', 'Design the user interface'],
     "answer": 'Verify individual components work as expected in isolation'},
    {"question": "What does 'UI' stand for?",
     "options": ['Unified Interface', 'User Interface', 'Universal Input', 'User Integration'],
     "answer": 'User Interface'},
    {"question": "Which of these is an example of a 'linear data structure'?",
     "options": ['Tree', 'Graph', 'Array', 'Hash map'],
     "answer": 'Array'},
    {"question": "What does 'AI' stand for?",
     "options": ['Automated Interface', 'Artificial Intelligence', 'Advanced Integration', 'Applied Informatics'],
     "answer": 'Artificial Intelligence'},
    {"question": "What is 'pseudocode'?",
     "options": ['A compiled programming language', 'An informal, high-level description of an algorithm', 'A type of encryption', 'A database query language'],
     "answer": 'An informal, high-level description of an algorithm'},
    {"question": "What does 'SaaS' stand for?",
     "options": ['Software as a Service', 'System as a Server', 'Software and Application Service', 'Server as a Solution'],
     "answer": 'Software as a Service'},
    {"question": "What is the purpose of 'version control'?",
     "options": ['Speed up code execution', 'Track and manage changes to code over time', 'Encrypt sensitive data', 'Design software architecture'],
     "answer": 'Track and manage changes to code over time'},
    {"question": "What is a 'boolean' value?",
     "options": ['A number between 0 and 1', 'A value that is either true or false', 'A text string', 'A type of loop'],
     "answer": 'A value that is either true or false'},
    {"question": "What does 'DDoS' stand for?",
     "options": ['Distributed Denial of Service', 'Direct Data over Server', 'Dynamic Data Storage', 'Double Data Security'],
     "answer": 'Distributed Denial of Service'},
    {"question": "What is the main advantage of a 'linked list' over an 'array'?",
     "options": ['Faster random access', 'Dynamic size and efficient insertion/deletion', 'Uses less memory always', 'Always sorted automatically'],
     "answer": 'Dynamic size and efficient insertion/deletion'},
    {"question": "What does 'ETL' stand for in data engineering?",
     "options": ['Extract, Transform, Load', 'Evaluate, Test, Launch', 'Export, Transfer, Log', 'Execute, Track, Load'],
     "answer": 'Extract, Transform, Load'},
    {"question": "What is a 'compiler error' also commonly called?",
     "options": ['Runtime error', 'Syntax or build error', 'Logical error', 'Network error'],
     "answer": 'Syntax or build error'},
    {"question": "What does 'MVC' stand for in software architecture?",
     "options": ['Model-View-Controller', 'Multi-Version Control', 'Main-View-Container', 'Module-Variable-Class'],
     "answer": 'Model-View-Controller'},
    {"question": "What is 'concurrency' in computing?",
     "options": ['Running a single task very fast', 'The ability of a system to handle multiple tasks making progress at overlapping times', 'A method of data encryption', 'A type of database index'],
     "answer": 'The ability of a system to handle multiple tasks making progress at overlapping times'},
    {"question": "What does 'CLI' stand for?",
     "options": ['Command Line Interface', 'Central Logic Index', 'Code Language Interpreter', 'Common Local Instance'],
     "answer": 'Command Line Interface'},
    {"question": "What is the purpose of an 'index' in a database?",
     "options": ['Encrypt table data', 'Speed up data retrieval operations', 'Delete duplicate rows', 'Backup the database'],
     "answer": 'Speed up data retrieval operations'},
    {"question": "What does 'OOP' stand for?",
     "options": ['Object-Oriented Programming', 'Optimal Operation Process', 'Ordered Output Protocol', 'Open Object Platform'],
     "answer": 'Object-Oriented Programming'},
    {"question": "What is a 'null' value generally used to represent?",
     "options": ['Zero as a number', 'The absence of a value', 'An error message', 'A default true/false'],
     "answer": 'The absence of a value'},
    {"question": "What does 'ISP' stand for?",
     "options": ['Internet Service Provider', 'Internal System Process', 'Integrated Server Protocol', 'Information Sharing Platform'],
     "answer": 'Internet Service Provider'},
    {"question": "What is the purpose of 'garbage collection' in programming languages?",
     "options": ['Delete user files', 'Automatically reclaim memory no longer in use', 'Remove unused code comments', 'Clean up log files'],
     "answer": 'Automatically reclaim memory no longer in use'},
    {"question": "What does 'DOM' stand for in web development?",
     "options": ['Document Object Model', 'Data Output Module', 'Dynamic Object Method', 'Document Operation Mode'],
     "answer": 'Document Object Model'},
    {"question": "What is a 'graph' data structure primarily used to represent?",
     "options": ['Sorted lists only', 'Relationships or connections between entities', 'Sequential text', 'Fixed-size collections'],
     "answer": 'Relationships or connections between entities'},
    {"question": "What does 'JWT' stand for?",
     "options": ['JSON Web Token', 'Java Web Toolkit', 'JavaScript Web Test', 'Joined Web Transfer'],
     "answer": 'JSON Web Token'},
    {"question": "What is 'latency' in networking?",
     "options": ['The total amount of data transferred', 'The delay before data transfer begins following an instruction', 'The number of connected devices', 'The strength of a signal'],
     "answer": 'The delay before data transfer begins following an instruction'},
    {"question": "What does 'RAID' stand for in storage systems?",
     "options": ['Redundant Array of Independent Disks', 'Rapid Access Internal Data', 'Recorded Array of Indexed Drives', 'Remote Access Integrated Disk'],
     "answer": 'Redundant Array of Independent Disks'},
    {"question": "What is the main goal of 'normalization' in database design?",
     "options": ['Increase data redundancy', 'Reduce data redundancy and improve data integrity', 'Make queries slower but safer', 'Encrypt all table columns'],
     "answer": 'Reduce data redundancy and improve data integrity'},
    {"question": "What does 'CSS' stand for?",
     "options": ['Cascading Style Sheets', 'Computer Style System', 'Creative Software Solutions', 'Central Style Sheet'],
     "answer": 'Cascading Style Sheets'},
    {"question": "What is an 'exception' in programming?",
     "options": ['A planned output value', 'An event that disrupts normal program flow, usually an error', 'A type of loop', 'A variable declaration'],
     "answer": 'An event that disrupts normal program flow, usually an error'},
    {"question": "What does 'YAML' commonly stand for (recursively)?",
     "options": ['Yet Another Markup Language', "YAML Ain't Markup Language", 'Your Application Markup Language', 'Yielded Attribute Markup List'],
     "answer": "YAML Ain't Markup Language"},
    {"question": "What is the purpose of a 'checksum'?",
     "options": ['Encrypt a file', 'Verify data integrity by detecting errors', 'Compress a file', 'Speed up file transfer'],
     "answer": 'Verify data integrity by detecting errors'},
    {"question": "What does 'FTP' stand for?",
     "options": ['File Transfer Protocol', 'Fast Transmission Process', 'File Type Protocol', 'Formatted Text Protocol'],
     "answer": 'File Transfer Protocol'},
    {"question": "What is 'abstraction' in programming?",
     "options": ['Hiding complex implementation details and showing only essential features', 'Combining multiple classes into one', 'Running code faster', 'Storing data in memory'],
     "answer": 'Hiding complex implementation details and showing only essential features'},
    {"question": "What does 'MAC address' stand for?",
     "options": ['Media Access Control address', 'Machine Application Code address', 'Main Access Channel address', 'Memory Allocation Code address'],
     "answer": 'Media Access Control address'},
    {"question": "What is a 'primary key' in a database table?",
     "options": ['A column that can have duplicate values', 'A unique identifier for each record in a table', 'A password for database access', 'A backup copy of the table'],
     "answer": 'A unique identifier for each record in a table'},
    {"question": "What does 'IoT' stand for?",
     "options": ['Internet of Things', 'Index of Terms', 'Interface of Technology', 'Integration of Tools'],
     "answer": 'Internet of Things'},
    {"question": "What is a 'breakpoint' used for in debugging?",
     "options": ['Permanently stop a program', 'Pause program execution at a specific point to inspect state', 'Delete a line of code', 'Compile the program'],
     "answer": 'Pause program execution at a specific point to inspect state'},
    {"question": "What does 'ASCII' stand for?",
     "options": ['American Standard Code for Information Interchange', 'Automated System for Computer Interface', 'Applied Standard Code for Internet Info', 'American System for Coded Instructions'],
     "answer": 'American Standard Code for Information Interchange'},
    {"question": "What is the purpose of a 'foreign key' in a relational database?",
     "options": ['Encrypt a table', 'Link records between two tables', 'Speed up all queries automatically', 'Store binary data'],
     "answer": 'Link records between two tables'},
    {"question": "What does 'RPC' stand for?",
     "options": ['Remote Procedure Call', 'Rapid Process Control', 'Recorded Program Code', 'Runtime Process Compiler'],
     "answer": 'Remote Procedure Call'},
    {"question": "What is 'middleware' in software architecture?",
     "options": ['The main database engine', 'Software that acts as a bridge between different applications or components', 'A type of hardware', 'The front-end user interface'],
     "answer": 'Software that acts as a bridge between different applications or components'},
    {"question": "What does 'XML' stand for?",
     "options": ['Extensible Markup Language', 'Extra Machine Language', 'External Markup List', 'Executable Markup Language'],
     "answer": 'Extensible Markup Language'},
    {"question": "What is the purpose of 'load testing' in software development?",
     "options": ['Check spelling errors in code', 'Evaluate how a system performs under expected or peak load', 'Test individual functions in isolation', 'Style the user interface'],
     "answer": 'Evaluate how a system performs under expected or peak load'},
    {"question": "What does 'GPU acceleration' generally help with?",
     "options": ['Managing file storage', 'Speeding up parallel computations like graphics or ML workloads', 'Encrypting network traffic', 'Formatting text documents'],
     "answer": 'Speeding up parallel computations like graphics or ML workloads'},
    {"question": "What is a 'sandbox' environment used for in software development?",
     "options": ['Permanently deleting old code', 'Safely testing code in an isolated environment without affecting production', 'Compiling code faster', 'Designing user interfaces'],
     "answer": 'Safely testing code in an isolated environment without affecting production'},
]
